package io.github.Leonardo0013YT.UltraSkyWars.enums;

public enum PerkType {

    FALL_REDUCTION,
    FIRE_DAMAGE_REDUCTION,
    SHOT_DAMAGE_REDUCTION,
    ANNO_O_MITE,
    ARROW_RECOVERY,
    BLAZING_ARROWS,
    BULLDOZER,
    ENDER_MASTERY,
    JUGGERNAUT,
    KNOWLEDGE,
    MINING_EXPERTISE,
    NOURISHMENT,
    RESISTENCE_START,
    SPEED_START,
    SAVIOR,

}